//------------------------------------------------------------------------------
// <auto-generated>
    // This code was generated by d2-i18n-generate.
    //
    // Changes to this file may cause incorrect behavior and will be lost if
    // the code is regenerated.
    // </auto-generated>
//------------------------------------------------------------------------------

import enTranslations from './en/translations.json';
import frTranslations from './fr/translations.json';

const namespace = 'hisengine-dashboard';

